/**
 * Script Include: SuperPromptProcessor
 *
 * Purpose:
 *   Parses a JSON payload generated by the AI "Super Prompt" and performs the
 *   requested ServiceNow administrative action.  Called from the
 *   "AI Super Prompt Executor" Flow Designer flow that is triggered when a
 *   user submits the corresponding Catalog Item.
 *
 * Supported actions (operation_details.action):
 *   - create_variable      : Creates a new variable on a Catalog Item
 *   - update_variable      : Updates an existing variable on a Catalog Item
 *   - update_catalog_item  : Updates fields on a Catalog Item record
 *   - create_user          : Creates a new sys_user record
 *   - update_user          : Updates fields on an existing sys_user record
 *
 * @param {string} jsonInput  - Raw JSON string from the catalog variable
 *                              v_json_payload.
 * @param {GlideRecord} ritmGr - The RITM GlideRecord so worknotes can be added.
 *
 * Usage in a Flow Designer Script step:
 *   var processor = new SuperPromptProcessor();
 *   processor.process(inputs.json_payload, inputs.ritm_gr);
 */
var SuperPromptProcessor = Class.create();

SuperPromptProcessor.prototype = {

    initialize: function () {},

    /**
     * Entry point.  Parses the JSON string and dispatches to the correct
     * handler method.
     *
     * @param {string}       jsonInput - Raw JSON string.
     * @param {GlideRecord}  ritmGr    - RITM record for worknote updates.
     * @returns {object} result - { success: boolean, message: string }
     */
    process: function (jsonInput, ritmGr) {
        var result = { success: false, message: '' };

        if (!jsonInput || jsonInput.trim() === '') {
            result.message = 'No JSON payload provided.';
            this._addWorknote(ritmGr, 'ERROR: ' + result.message);
            return result;
        }

        var data;
        try {
            data = JSON.parse(jsonInput);
        } catch (e) {
            result.message = 'Invalid JSON payload: ' + e.message;
            this._addWorknote(ritmGr, 'ERROR: ' + result.message);
            return result;
        }

        // Validate top-level required keys
        var validationError = this._validateSchema(data);
        if (validationError) {
            result.message = validationError;
            this._addWorknote(ritmGr, 'ERROR: ' + result.message);
            return result;
        }

        var action = data.operation_details.action;

        switch (action) {
            case 'create_variable':
                result = this._createVariable(data);
                break;
            case 'update_variable':
                result = this._updateVariable(data);
                break;
            case 'update_catalog_item':
                result = this._updateCatalogItem(data);
                break;
            case 'create_user':
                result = this._createUser(data);
                break;
            case 'update_user':
                result = this._updateUser(data);
                break;
            default:
                result.message = 'Unknown action: "' + action + '". ' +
                    'Supported actions: create_variable, update_variable, ' +
                    'update_catalog_item, create_user, update_user.';
        }

        // Always add the AI-generated worknote summary (or the error message)
        var noteText = result.success
            ? data.worknote_summary
            : 'ERROR: ' + result.message;
        this._addWorknote(ritmGr, noteText);

        return result;
    },

    // -------------------------------------------------------------------------
    // Action Handlers
    // -------------------------------------------------------------------------

    /**
     * Creates a new variable (item_option_new) on a Catalog Item.
     * Requires context.target_record_name to match a sc_cat_item name.
     */
    _createVariable: function (data) {
        var catItemSysId = this._getCatalogItemSysId(
            data.context.target_record_name
        );
        if (!catItemSysId) {
            return {
                success: false,
                message: 'Catalog item not found: "' +
                    data.context.target_record_name + '".'
            };
        }

        var gr = new GlideRecord('item_option_new');
        gr.initialize();
        gr.setValue('cat_item', catItemSysId);

        this._applyPayload(gr, data.payload);

        var sysId = gr.insert();
        if (!sysId) {
            return {
                success: false,
                message: 'Failed to insert variable record on "' +
                    data.context.target_record_name + '".'
            };
        }

        return {
            success: true,
            message: 'Variable created successfully (sys_id: ' + sysId + ').',
            sys_id: sysId
        };
    },

    /**
     * Updates an existing variable on a Catalog Item.
     * Uses payload.name to locate the variable within the correct cat_item.
     */
    _updateVariable: function (data) {
        var catItemSysId = this._getCatalogItemSysId(
            data.context.target_record_name
        );
        if (!catItemSysId) {
            return {
                success: false,
                message: 'Catalog item not found: "' +
                    data.context.target_record_name + '".'
            };
        }

        var variableName = data.payload.name || data.payload.question_text;
        if (!variableName) {
            return {
                success: false,
                message: 'payload.name or payload.question_text is required ' +
                    'to identify the variable to update.'
            };
        }

        var gr = new GlideRecord('item_option_new');
        gr.addQuery('cat_item', catItemSysId);
        gr.addQuery('name', variableName);
        gr.setLimit(1);
        gr.query();

        if (!gr.next()) {
            return {
                success: false,
                message: 'Variable "' + variableName + '" not found on "' +
                    data.context.target_record_name + '".'
            };
        }

        this._applyPayload(gr, data.payload);
        gr.update();

        return {
            success: true,
            message: 'Variable "' + variableName + '" updated successfully.'
        };
    },

    /**
     * Updates fields on a Catalog Item (sc_cat_item) record.
     */
    _updateCatalogItem: function (data) {
        var gr = new GlideRecord('sc_cat_item');
        gr.addQuery('name', data.context.target_record_name);
        gr.setLimit(1);
        gr.query();

        if (!gr.next()) {
            return {
                success: false,
                message: 'Catalog item not found: "' +
                    data.context.target_record_name + '".'
            };
        }

        this._applyPayload(gr, data.payload);
        gr.update();

        return {
            success: true,
            message: 'Catalog item "' + data.context.target_record_name +
                '" updated successfully.'
        };
    },

    /**
     * Creates a new user record (sys_user).
     */
    _createUser: function (data) {
        var gr = new GlideRecord('sys_user');
        gr.initialize();
        this._applyPayload(gr, data.payload);

        var sysId = gr.insert();
        if (!sysId) {
            return {
                success: false,
                message: 'Failed to create user "' +
                    data.context.target_record_name + '".'
            };
        }

        return {
            success: true,
            message: 'User "' + data.context.target_record_name +
                '" created successfully (sys_id: ' + sysId + ').',
            sys_id: sysId
        };
    },

    /**
     * Updates an existing user record (sys_user).
     * Uses payload.email or payload.user_name to locate the user.
     */
    _updateUser: function (data) {
        var lookupField = data.payload.email
            ? 'email'
            : (data.payload.user_name ? 'user_name' : null);

        if (!lookupField) {
            return {
                success: false,
                message: 'payload.email or payload.user_name is required to ' +
                    'identify the user to update.'
            };
        }

        var gr = new GlideRecord('sys_user');
        gr.addQuery(lookupField, data.payload[lookupField]);
        gr.setLimit(1);
        gr.query();

        if (!gr.next()) {
            return {
                success: false,
                message: 'User not found by ' + lookupField + ': "' +
                    data.payload[lookupField] + '".'
            };
        }

        this._applyPayload(gr, data.payload);
        gr.update();

        return {
            success: true,
            message: 'User "' + data.context.target_record_name +
                '" updated successfully.'
        };
    },

    // -------------------------------------------------------------------------
    // Helper Methods
    // -------------------------------------------------------------------------

    /**
     * Validates that all required top-level keys exist in the parsed object.
     *
     * @param {object} data
     * @returns {string|null} Error message string or null if valid.
     */
    _validateSchema: function (data) {
        var required = [
            'operation_details',
            'context',
            'payload',
            'worknote_summary'
        ];

        for (var i = 0; i < required.length; i++) {
            if (!data[required[i]]) {
                return 'Missing required key: "' + required[i] + '".';
            }
        }

        if (!data.operation_details.action) {
            return 'Missing required key: "operation_details.action".';
        }

        if (!data.operation_details.target_table) {
            return 'Missing required key: "operation_details.target_table".';
        }

        if (!data.context.target_record_name) {
            return 'Missing required key: "context.target_record_name".';
        }

        return null;
    },

    /**
     * Looks up a Catalog Item by name and returns its sys_id.
     *
     * @param {string} name - The catalog item name.
     * @returns {string|null}
     */
    _getCatalogItemSysId: function (name) {
        var gr = new GlideRecord('sc_cat_item');
        gr.addQuery('name', name);
        gr.setLimit(1);
        gr.query();
        return gr.next() ? gr.getUniqueValue() : null;
    },

    /**
     * Applies every key-value pair from a plain payload object to a
     * GlideRecord using setValue.
     *
     * @param {GlideRecord} gr
     * @param {object}      payload
     */
    _applyPayload: function (gr, payload) {
        for (var field in payload) {
            if (Object.prototype.hasOwnProperty.call(payload, field)) {
                gr.setValue(field, payload[field]);
            }
        }
    },

    /**
     * Adds a work note to the supplied RITM GlideRecord.
     *
     * @param {GlideRecord} ritmGr
     * @param {string}      note
     */
    _addWorknote: function (ritmGr, note) {
        if (!ritmGr || !note) {
            return;
        }
        try {
            ritmGr.work_notes = '[AI Super Prompt] ' + note;
            ritmGr.setWorkflow(false);
            ritmGr.update();
        } catch (e) {
            gs.error('SuperPromptProcessor._addWorknote: ' + e.message);
        }
    },

    type: 'SuperPromptProcessor'
};
