#!/usr/bin/env python3
"""
deploy_via_table_api.py
=======================
Deploys (or updates) the Snow Super Prompt components directly into a
ServiceNow instance using the REST Table API.

This script is an **alternative** to importing the update set XML.  Use it
when the update set import is not working or when you want to automate
deployments from a CI/CD pipeline.

Components deployed
-------------------
1. Script Include  — SuperPromptProcessor  (sys_script_include)
2. Catalog Item    — AI Super Prompt Executor  (sc_cat_item)
3. Variables       — v_json_payload, v_table_schema, v_existing_records_xml
                     (item_option_new)

Requirements
------------
  Python 3.7+
  pip install requests

Usage
-----
  python deploy_via_table_api.py \\
      --instance  https://dev12345.service-now.com \\
      --username  admin \\
      --password  <password>

  # Use environment variables instead of CLI flags:
  export SN_INSTANCE=https://dev12345.service-now.com
  export SN_USERNAME=admin
  export SN_PASSWORD=<password>
  python deploy_via_table_api.py

Options
-------
  --instance   Base URL of the ServiceNow instance (no trailing slash).
  --username   ServiceNow admin username.
  --password   ServiceNow admin password.
  --scope      Application scope for newly created records (default: global).
  --dry-run    Print what would be done without making any API calls.
"""

import argparse
import json
import os
import sys
from pathlib import Path

try:
    import requests
    from requests.auth import HTTPBasicAuth
except ImportError:
    sys.exit(
        "ERROR: 'requests' library not found.\n"
        "Install it with:  pip install requests"
    )

# ---------------------------------------------------------------------------
# Paths (relative to this script's location)
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
SCRIPT_INCLUDE_PATH = REPO_ROOT / "src" / "script_includes" / "SuperPromptProcessor.js"

# ---------------------------------------------------------------------------
# Record definitions
# ---------------------------------------------------------------------------

CATALOG_ITEM_NAME = "AI Super Prompt Executor"

VARIABLES = [
    {
        "name": "v_json_payload",
        "question_text": "JSON Payload (paste AI-generated output here)",
        "label": "JSON Payload",
        "type": "8",          # Multi-line Text
        "mandatory": "true",
        "order": "100",
        "help_tag": (
            "Paste the raw JSON that was generated by the AI chatbot here.\n"
            "Do not modify the JSON — submit it exactly as produced by the AI."
        ),
    },
    {
        "name": "v_table_schema",
        "question_text": "Target Table Schema / Field Dictionary (optional)",
        "label": "Table Schema (optional)",
        "type": "8",
        "mandatory": "false",
        "order": "200",
        "help_tag": (
            "Optional. Paste the table's field dictionary XML (or a plain list of\n"
            "field names and types) here so the AI can verify field names and\n"
            "identify required fields.\n\n"
            "To export from ServiceNow:\n"
            "  System Definition > Tables & Columns > [your table] > Show Dictionary\n"
            "Then right-click the list header and choose Export > XML."
        ),
    },
    {
        "name": "v_existing_records_xml",
        "question_text": "Existing Records XML for AI reference (optional)",
        "label": "Existing Records XML (optional)",
        "type": "8",
        "mandatory": "false",
        "order": "300",
        "help_tag": (
            "Optional. Paste one or more existing records from the target table\n"
            "exported as XML.  The AI uses these records as a reference to\n"
            "understand the correct data format and field values.\n\n"
            "To export from ServiceNow:\n"
            "  1. Open the target table list view.\n"
            "  2. Right-click any row header.\n"
            "  3. Choose Export > XML."
        ),
    },
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

class SNClient:
    """Thin wrapper around the ServiceNow Table REST API."""

    HEADERS = {
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    def __init__(self, instance: str, username: str, password: str,
                 dry_run: bool = False):
        self.base = instance.rstrip("/")
        self.auth = HTTPBasicAuth(username, password)
        self.dry_run = dry_run

    def _url(self, table: str, sys_id: str = "") -> str:
        path = f"/api/now/table/{table}"
        if sys_id:
            path += f"/{sys_id}"
        return self.base + path

    def get(self, table: str, query: str) -> list:
        """Return all records matching sysparm_query."""
        if self.dry_run:
            return []   # Treat everything as "not found" in dry-run
        url = self._url(table)
        resp = requests.get(
            url,
            params={"sysparm_query": query, "sysparm_limit": "10"},
            headers=self.HEADERS,
            auth=self.auth,
            timeout=30,
        )
        resp.raise_for_status()
        return resp.json().get("result", [])

    def create(self, table: str, body: dict) -> dict:
        """Insert a new record and return the created record dict."""
        url = self._url(table)
        if self.dry_run:
            print(f"  [DRY-RUN] POST {url}")
            print(f"            body = {json.dumps(body, indent=12)[:300]}")
            return {"sys_id": "DRY_RUN", "name": body.get("name", "")}
        resp = requests.post(
            url, json=body, headers=self.HEADERS, auth=self.auth, timeout=30
        )
        resp.raise_for_status()
        return resp.json().get("result", {})

    def update(self, table: str, sys_id: str, body: dict) -> dict:
        """Update an existing record (PATCH) and return the updated record."""
        url = self._url(table, sys_id)
        if self.dry_run:
            print(f"  [DRY-RUN] PATCH {url}")
            print(f"            body = {json.dumps(body, indent=12)[:300]}")
            return {"sys_id": sys_id}
        resp = requests.patch(
            url, json=body, headers=self.HEADERS, auth=self.auth, timeout=30
        )
        resp.raise_for_status()
        return resp.json().get("result", {})

    def upsert(self, table: str, query: str, body: dict,
               label: str = "") -> tuple:
        """
        Create or update a record.

        Returns (record_dict, created) where created=True means a new record
        was inserted.
        """
        existing = self.get(table, query)
        label_str = label or body.get("name", table)
        if existing:
            sys_id = existing[0]["sys_id"]
            print(f"  UPDATE  [{table}]  {label_str}  (sys_id: {sys_id})")
            record = self.update(table, sys_id, body)
            return record, False
        else:
            print(f"  CREATE  [{table}]  {label_str}")
            record = self.create(table, body)
            return record, True


# ---------------------------------------------------------------------------
# Deployment steps
# ---------------------------------------------------------------------------

def _resolve_scope_sys_id(client: SNClient, scope_name: str) -> "str | None":
    """Return the sys_id of a sys_scope record, or None if not found."""
    rows = client.get("sys_scope", f"scope={scope_name}")
    if rows:
        return rows[0]["sys_id"]
    # Try by name as a fallback
    rows = client.get("sys_scope", f"name={scope_name}")
    return rows[0]["sys_id"] if rows else None


def deploy_script_include(client: SNClient, scope_sys_id: "str | None") -> str:
    """Deploy (create or update) the SuperPromptProcessor Script Include."""
    print("\n--- Script Include ---")

    script_body = SCRIPT_INCLUDE_PATH.read_text(encoding="utf-8")

    body: dict = {
        "name": "SuperPromptProcessor",
        "api_name": "global.SuperPromptProcessor",
        "active": "true",
        "access": "public",
        "description": (
            "Parses AI Super Prompt JSON payloads and performs the requested "
            "ServiceNow administrative actions."
        ),
        "script": script_body,
    }
    if scope_sys_id:
        body["sys_scope"] = scope_sys_id

    record, _ = client.upsert(
        "sys_script_include",
        "name=SuperPromptProcessor",
        body,
        label="SuperPromptProcessor",
    )
    sys_id = record.get("sys_id", "")
    print(f"         sys_id: {sys_id}")
    return sys_id


def deploy_catalog_item(client: SNClient, scope_sys_id: "str | None") -> str:
    """Deploy (create or update) the AI Super Prompt Executor catalog item."""
    print("\n--- Catalog Item ---")

    description_html = """<p>Use this catalog item to submit a <strong>ServiceNow administrative task</strong>
that was generated by the <em>AI Super Prompt</em>.</p>

<h3>How to use</h3>
<ol>
  <li>Open your AI chatbot (Copilot, ChatGPT, Gemini, etc.).</li>
  <li>Paste the contents of <code>super_prompt.txt</code> to initialise the assistant.</li>
  <li>Describe the ServiceNow change you need in plain English.</li>
  <li>Copy the JSON output produced by the AI.</li>
  <li>Paste it into the <strong>JSON Payload</strong> field below and submit.</li>
</ol>

<p>The attached flow will parse your JSON and automatically perform the requested
change in your ServiceNow instance, then add a work note to this request with
a summary of what was done and links to every record that was affected.</p>"""

    body: dict = {
        "name": CATALOG_ITEM_NAME,
        "short_description": (
            "Submit an AI-generated JSON payload to automate a ServiceNow admin task"
        ),
        "description": description_html,
        "active": "true",
        "sys_class_name": "sc_cat_item",
    }
    if scope_sys_id:
        body["sys_scope"] = scope_sys_id

    record, _ = client.upsert(
        "sc_cat_item",
        f"name={CATALOG_ITEM_NAME}",
        body,
        label=CATALOG_ITEM_NAME,
    )
    sys_id = record.get("sys_id", "")
    print(f"         sys_id: {sys_id}")
    return sys_id


def deploy_variables(
    client: SNClient, cat_item_sys_id: str, scope_sys_id: "str | None"
) -> None:
    """Deploy (create or update) the three catalog item variables."""
    print("\n--- Catalog Item Variables ---")

    for var_def in VARIABLES:
        body: dict = {
            "cat_item": cat_item_sys_id,
            "name": var_def["name"],
            "question_text": var_def["question_text"],
            "label": var_def["label"],
            "type": var_def["type"],
            "mandatory": var_def["mandatory"],
            "order": var_def["order"],
            "help_tag": var_def["help_tag"],
            "active": "true",
        }
        if scope_sys_id:
            body["sys_scope"] = scope_sys_id

        record, _ = client.upsert(
            "item_option_new",
            f"cat_item={cat_item_sys_id}^name={var_def['name']}",
            body,
            label=var_def["name"],
        )
        print(f"         sys_id: {record.get('sys_id', '')}")


# ---------------------------------------------------------------------------
# Summary printer
# ---------------------------------------------------------------------------

def _print_summary(instance: str, si_sys_id: str, ci_sys_id: str) -> None:
    base = instance.rstrip("/")
    print("\n" + "=" * 60)
    print("Deployment complete.  Records affected:")
    print("=" * 60)

    records = [
        ("Script Include", "sys_script_include", si_sys_id),
        ("Catalog Item",   "sc_cat_item",        ci_sys_id),
    ]
    for label, table, sys_id in records:
        if sys_id and sys_id != "DRY_RUN":
            url = f"{base}/{table}.do?sys_id={sys_id}"
        else:
            url = "(dry-run — no sys_id)"
        print(f"  {label:<22}  {table:<25}  {url}")

    print("=" * 60)
    print(
        "\nNext steps:\n"
        "  1. Activate the 'AI Super Prompt Executor Flow' in Flow Designer.\n"
        "  2. Assign the catalog item to a Service Catalog and category.\n"
        "  3. Confirm the Script Include is active (System Definition > Script Includes)."
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Deploy Snow Super Prompt components via ServiceNow Table API.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--instance",
        default=os.environ.get("SN_INSTANCE", ""),
        help="ServiceNow instance base URL (env: SN_INSTANCE).",
    )
    parser.add_argument(
        "--username",
        default=os.environ.get("SN_USERNAME", ""),
        help="Admin username (env: SN_USERNAME).",
    )
    parser.add_argument(
        "--password",
        default=os.environ.get("SN_PASSWORD", ""),
        help="Admin password (env: SN_PASSWORD).",
    )
    parser.add_argument(
        "--scope",
        default=os.environ.get("SN_SCOPE", "global"),
        help="Application scope for new records (default: global).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned API calls without executing them.",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    # Validate required arguments
    missing = [
        name for name, val in [
            ("--instance / SN_INSTANCE", args.instance),
            ("--username / SN_USERNAME", args.username),
            ("--password / SN_PASSWORD", args.password),
        ]
        if not val
    ]
    if missing:
        sys.exit("ERROR: Missing required arguments:\n  " + "\n  ".join(missing))

    if not SCRIPT_INCLUDE_PATH.exists():
        sys.exit(
            f"ERROR: Script Include source file not found:\n  {SCRIPT_INCLUDE_PATH}"
        )

    if args.dry_run:
        print("[DRY-RUN MODE] No changes will be made to the instance.\n")

    client = SNClient(
        instance=args.instance,
        username=args.username,
        password=args.password,
        dry_run=args.dry_run,
    )

    print(f"Target instance : {args.instance}")
    print(f"Scope           : {args.scope}")

    # Resolve scope sys_id once
    scope_sys_id: "str | None" = None
    if args.scope and args.scope.lower() != "global":
        scope_sys_id = _resolve_scope_sys_id(client, args.scope)
        if not scope_sys_id and not args.dry_run:
            print(
                f"WARNING: Scope '{args.scope}' not found in sys_scope. "
                "Records will be created in the default scope."
            )

    # Deploy components
    si_sys_id = deploy_script_include(client, scope_sys_id)
    ci_sys_id = deploy_catalog_item(client, scope_sys_id)
    deploy_variables(client, ci_sys_id, scope_sys_id)

    _print_summary(args.instance, si_sys_id, ci_sys_id)


if __name__ == "__main__":
    main()
